spring:
  application:
    name: @project.artifactId@

pltf:
  plugin-path: ./plugins

info:
  app:
    name: ${spring.application.name}
    version: @project.version@
    encoding: @project.build.sourceEncoding@
  java:
    version: @java.version@