spring:
  application:
    name: @project.artifactId@

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    health:
#      show-details: always

pltf:
  pluginDir: './plugins'

info:
  app:
    name: ${spring.application.name}
    version: @project.version@
  java:
    version: @java.version@